# Generated by Django 5.0.7 on 2024-11-14 14:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, choices=[('냉장', '냉장'), ('냉동', '냉동'), ('실외', '실외')], max_length=255, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('memo', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('user', models.ForeignKey(default='', max_length=20, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'production',
            },
        ),
    ]
