# Generated by Django 5.0.7 on 2024-11-19 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('food_name', models.CharField(max_length=100)),
                ('material_name', models.TextField()),
            ],
            options={
                'db_table': 'recipe',
            },
        ),
    ]

