# Generated by Django 5.0.7 on 2024-11-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_waste', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodwaste',
            name='quantity',
            field=models.IntegerField(choices=[(0, '1L'), (1, '3L'), (2, '5L'), (3, '10L'), (4, '20L')], default=0, help_text='0 : 1L, 1 : 3L, 2 : 5L, 3 : 10L, 4 : 20L'),
        ),
    ]

